Create own ansible base image

diff --git a/services/ansibler/Dockerfile b/services/ansibler/Dockerfile
--- a/services/ansibler/Dockerfile
+++ b/services/ansibler/Dockerfile
@@ -1,3 +1,45 @@
+#Ansible base image inspired by https://github.com/cytopia/docker-ansible
+FROM alpine:3.16 as ansible-base
+
+# Package required tools
+RUN set -eux \
+  && apk add --update --no-cache bc cargo cmake curl g++ \
+  gcc git libffi-dev libxml2-dev libxslt-dev make musl-dev \
+  openssl-dev py3-pip python3 python3-dev rust
+
+# Fix: ansible --version: libyaml = True
+# https://www.jeffgeerling.com/blog/2021/ansible-might-be-running-slow-if-libyaml-not-available
+RUN set -eux \
+  && apk add --update --no-cache \
+  py3-yaml && python3 -c 'import _yaml'
+
+# Pip required tools for all flavour's "builder" stage
+RUN set -eux \ 
+  && pip3 install --no-cache-dir --no-compile \
+  wheel && pip3 install --no-cache-dir --no-compile \
+  Jinja2 MarkupSafe PyNaCl \
+  bcrypt cffi cryptography pycparser
+
+# Install ansible
+RUN set -eux \
+  && pip3 install --no-cache-dir --no-binary pyyaml "ansible-core>=2.11,<2.12" \
+  && ansible --version | grep ^ansible | grep -E "2.11\.[0-9]+" \
+  && ansible-playbook --version | grep ^ansible | grep -E "2.11\.[0-9]+" \
+  && ansible-galaxy --version | grep ^ansible | grep -E "2.11\.[0-9]+" \
+  && find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
+  && find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf
+
+# Python packages (copied to final image)
+RUN set -eux \
+  && apk add --no-cache  \
+  && pip3 install --no-cache-dir --no-compile junit-xml lxml paramiko \
+  && find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
+  && find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf
+
+# Cleanup
+RUN set -eux \
+  && pip3 uninstall --yes setuptools wheel
+
 FROM golang:1.19.2 AS build
 
 #Unset the GOPATH
@@ -35,14 +77,38 @@ WORKDIR /go/services/ansibler/server
 RUN CGO_ENABLED=0 go build
 
 #Use alpine based ansible image
-FROM cytopia/ansible:2.11
+FROM alpine:3.16
 
-#Copy the binaries to empty base image
+RUN set -eux \
+  && apk add --no-cache \
+  libgcc py3-pip python3 yaml \
+  && ln -sf /usr/bin/python3 /usr/bin/python \
+  && ln -sf ansible /usr/bin/ansible-config \
+  && ln -sf ansible /usr/bin/ansible-console \
+  && ln -sf ansible /usr/bin/ansible-doc \
+  && ln -sf ansible /usr/bin/ansible-galaxy \
+  && ln -sf ansible /usr/bin/ansible-inventory \
+  && ln -sf ansible /usr/bin/ansible-playbook \
+  && ln -sf ansible /usr/bin/ansible-pull \
+  && ln -sf ansible /usr/bin/ansible-test \
+  && ln -sf ansible /usr/bin/ansible-vault \
+  && find /usr/lib/ -name '__pycache__' -print0 | xargs -0 -n1 rm -rf \
+  && find /usr/lib/ -name '*.pyc' -print0 | xargs -0 -n1 rm -rf
+
+#Copy the binaries to base image
 COPY --from=build /go/services/ansibler/server/server /bin/services/ansibler/server/server
 COPY --from=build /bin/grpc_health_probe /bin/grpc_health_probe
 COPY --from=build /bin/grpc_health_probe-Liveness /bin/grpc_health_probe-Liveness
 COPY --from=build /go/services/ansibler/templates /bin/services/ansibler/templates
 COPY --from=build /go/services/ansibler/server/ansible-playbooks /bin/services/ansibler/server/ansible-playbooks
+
+#Copy ansible
+COPY --from=ansible-base /usr/lib/python3.10/site-packages/ /usr/lib/python3.10/site-packages/
+COPY --from=ansible-base /usr/bin/ansible /usr/bin/ansible
+COPY --from=ansible-base /usr/bin/ansible-connection /usr/bin/ansible-connection
+
+# Pre-compile Python for better performance
+RUN set -eux && python3 -m compileall /usr/lib/python3.8
 
 RUN apk update && apk add -q bash
 
